backend:
  name: github
  repo: tlskillman/michaelspencepoet-site
  branch: main

publish_mode: editorial_workflow

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - label: "Biography"
        name: "bio"
        file: "index.html"
        fields:
          - {label: "Biography Text", name: "body", widget: "markdown"}
      - label: "Published Works"
        name: "works"
        file: "index.html"
        fields:
          - {label: "Works Section", name: "body", widget: "markdown"}
      - label: "Poetic Themes"
        name: "themes"
        file: "index.html"
        fields:
          - {label: "Themes", name: "body", widget: "markdown"}
